version: '3.8'
services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - D:/scanner_results:/scanner_results
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    depends_on:
      scanner-api:
        condition: service_healthy
    networks:
      - scanner-network

  scanner-api:
    build:
      context: .
    image: scanner-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://harshitadutt267_db_user:Harshitadutt%4027@cluster-engine.o4cj0fm.mongodb.net/?appName=Cluster-engine
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - scanner-network

networks:
  scanner-network:
    driver: bridge

volumes:
  jenkins_home:
