version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "9090:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    depends_on:
      - scanner-api

  scanner-api:
    build:
      context: .
    image: scanner-api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://harshitadutt267_db_user:Harshitadutt%4027@cluster-engine.o4cj0fm.mongodb.net/?appName=Cluster-engine

volumes:
  jenkins_home:
